### ISSUE TITLE
typescript type definition is wrong

### ISSUE THREAD

**Issue by yyyhehehe** [react-spring/react-with-gesture#21]
```typescript
<Gesture
  onAction={(e) => {
    console.log(e.xy); // type check failed. but value existed.
    console.log(e.xDelta); // type check passed. but value is undefined.
    console.log(e.yDelta); // type check passed. but value is undefined.
  }>
//...
```

`GestureState` does not describe actual value passed to event handler.

**Comment by drcmda** [comment]
There currently aren't any definitions, there's this file: https://github.com/drcmda/react-with-gesture/blob/master/index.d._ts but outdated. I don't know/use TS, relying on contributions.

**Comment by forNope** [comment]
@yyyhehehe  I think it can work for typescript now

**Comment by ralexand56** [comment]
These types are all screwed up. This:
const [bind, { local: [x, y] }] = useGesture()

gives an error that useGesture doesn't accept an array as a return value.
